USE [RH]
GO

/****** Object:  Table [dbo].[Tpuesto]    Script Date: 26/06/2022 23:48:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tpuesto](
	[PpuestoID] [int] IDENTITY(1,1) NOT NULL,
	[Pnombre] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Tpuesto] PRIMARY KEY CLUSTERED 
(
	[PpuestoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


