//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRH_Pertec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templeado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Templeado()
        {
            this.Tpuestofechas = new HashSet<Tpuestofecha>();
        }
    
        public int EempleadoID { get; set; }
        public string Enombre { get; set; }
        public string Eapellido { get; set; }
        public string Eapellido2 { get; set; }
        public string Etelefono { get; set; }
        public string Ecorreo { get; set; }
        public int EpuestoID { get; set; }
    
        public virtual Tpuesto Tpuesto { get; set; }
        public virtual Tempresafecha Tempresafecha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tpuestofecha> Tpuestofechas { get; set; }
    }
}
