//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRH_Pertec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tpuestofecha
    {
        public int PEfechaXempresaID { get; set; }
        public int PEempleadoID { get; set; }
        public Nullable<int> PEpuestoID { get; set; }
        public Nullable<System.DateTime> PEfechainicio { get; set; }
        public Nullable<System.DateTime> PEfechafin { get; set; }
    
        public virtual Templeado Templeado { get; set; }
    }
}
